[build]
  base    = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Fix React Router — redirect all routes to index.html
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
